import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'ar' | 'pt' | 'hi';

interface Translations {
  [key: string]: string;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Translations> = {
  ru: {
    // Header
    home: 'Главная',
    howToStart: 'Как начать',
    about: 'О нас',
    marketplace: 'Маркетплейс',
    dashboard: 'Панель',
    connectWallet: 'Подключить кошелек',
    disconnect: 'Отключить',
    
    // Hero section
    tokenizeRealAssets: 'Токенизируйте',
    realAssets: 'реальные активы',
    heroSubtitle: 'Превратите недвижимость, товары и другие активы в цифровые токены с помощью блокчейн технологий',
    tokenLimitPerAsset: 'Лимит токенов на актив',
    stableTokens: 'Стабильных токенов',
    assetTrading: 'Торговля активами',
    startTokenization: 'Начать токенизацию',
    exploreMarketplace: 'Изучить маркетплейс',
    
    // Features
    highLiquidity: 'Высокая ликвидность',
    highLiquidityDesc: 'Торгуйте активами 24/7 на децентрализованной платформе',
    security: 'Безопасность',
    securityDesc: 'Защищено блокчейн технологиями и смарт-контрактами',
    tripleTokenization: 'Тройная токенизация',
    tripleTokenizationDesc: 'AST, AGT и ABT токены для максимальной гибкости',
    
    // How to start
    howToStartTitle: 'Как начать работу',
    howToStartDescription: 'Простые шаги для начала токенизации ваших активов',
    step1Title: 'Подключите кошелек',
    step1Description: 'Подключите MetaMask или другой совместимый кошелек',
    step2Title: 'Пополните баланс',
    step2Description: 'Добавьте COSMO токены для оплаты комиссий',
    step3Title: 'Создайте актив',
    step3Description: 'Загрузите информацию о вашем активе',
    step4Title: 'Торгуйте токенами',
    step4Description: 'Торгуйте токенами на маркетплейсе',
    
    // About
    aboutTitle: 'О платформе',
    aboutDescription: 'Cosmo RWA - это революционная платформа для токенизации реальных активов',
    missionTitle: 'Наша миссия',
    missionDescription: 'Мы стремимся сделать инвестиции в реальные активы доступными для всех через блокчейн технологии',
    featuresTitle: 'Наши особенности',
    feature1: 'Безопасность на основе блокчейна',
    feature2: 'Глобальная доступность',
    feature3: 'Мгновенные транзакции',
    feature4: 'Сообщество инвесторов',
    
    // Asset creation
    connectMetaMask: 'Подключите MetaMask',
    connectWalletToCreateAsset: 'Пожалуйста, подключите кошелек для создания актива',
    back: 'Назад',
    realEstate: 'Недвижимость',
    goods: 'Товары',
    art: 'Искусство',
    collectibles: 'Коллекционные предметы',
    other: 'Другое',
    assetName: 'Название актива',
    assetNamePlaceholder: 'Квартира в центре Алматы',
    assetDescription: 'Описание актива',
    assetDescriptionPlaceholder: 'Например: Квартира в центре Алматы, 2 комнаты, 65 кв.м.',
    assetType: 'Тип актива',
    selectAssetType: 'Выберите тип актива',
    assetValue: 'Стоимость актива (USD)',
    location: 'Местоположение',
    locationPlaceholder: 'Введите местоположение',
    imageUrlOptional: 'URL изображения (необязательно)',
    tokenCalculationPreview: 'Предварительный расчет стоимости токенов',
    perToken: 'за токен',
    tokenLimitInfo: 'Общая сумма распределяется между токенами AST, AGT и ABT',
    creatingAsset: 'Создание актива...',
    createAsset: 'Создать актив',
    success: 'Успех',
    assetCreatedSuccessfully: 'Актив успешно создан с токенами',
    error: 'Ошибка',
    connectWalletFirst: 'Пожалуйста, сначала подключите кошелек',
    assetCreationError: 'Ошибка при создании актива',
    backToDashboard: 'Назад к панели',
    loading: 'Загрузка...',
    balance: 'Баланс',
    cosmoBalance: 'Баланс COSMO',
    bnbBalance: 'Баланс BNB',
    totalValue: 'Общая стоимость',
    
    // Dashboard
    quickActions: 'Быстрые действия',
    tokenizeYourAsset: 'Токенизируйте ваш актив',
    tradeAssetTokens: 'Торгуйте токенами активов',
    loans: 'Займы',
    loansWithTokenCollateral: 'Займы под залог токенов',
    defiSwap: 'DeFi обмен',
    exchangeTokens: 'Обменять токены',
    open: 'Открыть',
  },
  en: {
    // Header
    home: 'Home',
    howToStart: 'How to Start',
    about: 'About',
    marketplace: 'Marketplace',
    dashboard: 'Dashboard',
    connectWallet: 'Connect Wallet',
    disconnect: 'Disconnect',
    
    // Hero section
    tokenizeRealAssets: 'Tokenize',
    realAssets: 'real assets',
    heroSubtitle: 'Turn real estate, goods and other assets into digital tokens using blockchain technology',
    tokenLimitPerAsset: 'Token limit per asset',
    stableTokens: 'Stable tokens',
    assetTrading: 'Asset trading',
    startTokenization: 'Start Tokenization',
    exploreMarketplace: 'Explore Marketplace',
    
    // Features
    highLiquidity: 'High Liquidity',
    highLiquidityDesc: 'Trade assets 24/7 on a decentralized platform',
    security: 'Security',
    securityDesc: 'Protected by blockchain technology and smart contracts',
    tripleTokenization: 'Triple Tokenization',
    tripleTokenizationDesc: 'AST, AGT and ABT tokens for maximum flexibility',
    
    // How to start
    howToStartTitle: 'How to Get Started',
    howToStartDescription: 'Simple steps to start tokenizing your assets',
    step1Title: 'Connect Wallet',
    step1Description: 'Connect MetaMask or other compatible wallet',
    step2Title: 'Fund Balance',
    step2Description: 'Add COSMO tokens to pay fees',
    step3Title: 'Create Asset',
    step3Description: 'Upload information about your asset',
    step4Title: 'Trade Tokens',
    step4Description: 'Trade tokens on the marketplace',
    
    // About
    aboutTitle: 'About Platform',
    aboutDescription: 'Cosmo RWA is a revolutionary platform for real asset tokenization',
    missionTitle: 'Our Mission',
    missionDescription: 'We strive to make real asset investments accessible to everyone through blockchain technology',
    featuresTitle: 'Our Features',
    feature1: 'Blockchain-based security',
    feature2: 'Global accessibility',
    feature3: 'Instant transactions',
    feature4: 'Investor community',
    
    // Asset creation
    connectMetaMask: 'Connect MetaMask',
    connectWalletToCreateAsset: 'Please connect your wallet to create an asset',
    back: 'Back',
    realEstate: 'Real Estate',
    goods: 'Goods',
    art: 'Art',
    collectibles: 'Collectibles',
    other: 'Other',
    assetName: 'Asset Name',
    assetNamePlaceholder: 'Enter asset name',
    assetDescription: 'Asset Description',
    assetDescriptionPlaceholder: 'e.g. Apartment in downtown Moscow, 2 rooms, 65 sqm',
    assetType: 'Asset Type',
    selectAssetType: 'Select asset type',
    assetValue: 'Asset Value (USD)',
    location: 'Location',
    locationPlaceholder: 'Enter location',
    imageUrlOptional: 'Image URL (optional)',
    tokenCalculationPreview: 'Token price calculation preview',
    perToken: 'per token',
    tokenLimitInfo: 'Total value is distributed among AST, AGT, and ABT tokens',
    creatingAsset: 'Creating asset...',
    createAsset: 'Create Asset',
    success: 'Success',
    assetCreatedSuccessfully: 'Asset created successfully with tokens',
    error: 'Error',
    connectWalletFirst: 'Please connect your wallet first',
    assetCreationError: 'Error creating asset',
    backToDashboard: 'Back to Dashboard',
    loading: 'Loading...',
    balance: 'Balance',
    cosmoBalance: 'COSMO Balance',
    bnbBalance: 'BNB Balance',
    totalValue: 'Total Value',
    
    // Dashboard
    quickActions: 'Quick Actions',
    tokenizeYourAsset: 'Tokenize your asset',
    tradeAssetTokens: 'Trade asset tokens',
    loans: 'Loans',
    loansWithTokenCollateral: 'Loans with token collateral',
    defiSwap: 'DeFi Swap',
    exchangeTokens: 'Exchange tokens',
    open: 'Open',
  },
  es: {
    // Header
    home: 'Inicio',
    howToStart: 'Cómo empezar',
    about: 'Acerca de',
    marketplace: 'Mercado',
    dashboard: 'Panel',
    connectWallet: 'Conectar billetera',
    disconnect: 'Desconectar',
    tokenizeRealAssets: 'Tokenizar',
    realAssets: 'activos reales',
    heroSubtitle: 'Convierte bienes raíces, mercancías y otros activos en tokens digitales usando tecnología blockchain',
    tokenLimitPerAsset: 'Límite de tokens por activo',
    stableTokens: 'Tokens estables',
    assetTrading: 'Comercio de activos',
    startTokenization: 'Comenzar tokenización',
    exploreMarketplace: 'Explorar mercado',
    highLiquidity: 'Alta liquidez',
    highLiquidityDesc: 'Comercia activos 24/7 en una plataforma descentralizada',
    security: 'Seguridad',
    securityDesc: 'Protegido por tecnología blockchain y contratos inteligentes',
    tripleTokenization: 'Triple tokenización',
    tripleTokenizationDesc: 'Tokens AST, AGT y ABT para máxima flexibilidad',
    connectMetaMask: 'Conectar MetaMask',
    connectWalletToCreateAsset: 'Por favor, conecta tu billetera para crear un activo',
    back: 'Atrás',
    realEstate: 'Bienes raíces',
    goods: 'Bienes',
    art: 'Arte',
    collectibles: 'Coleccionables',
    other: 'Otro',
    assetName: 'Nombre del activo',
    assetNamePlaceholder: 'Ingrese el nombre del activo',
    assetDescription: 'Descripción del activo',
    assetDescriptionPlaceholder: 'Ejemplo: Apartamento en el centro de Moscú, 2 habitaciones, 65 m²',
    assetType: 'Tipo de activo',
    selectAssetType: 'Seleccione tipo de activo',
    assetValue: 'Valor del activo (USD)',
    location: 'Ubicación',
    locationPlaceholder: 'Ingrese la ubicación',
    imageUrlOptional: 'URL de la imagen (opcional)',
    tokenCalculationPreview: 'Vista previa del cálculo del precio del token',
    perToken: 'por token',
    tokenLimitInfo: 'El valor total se distribuye entre los tokens AST, AGT y ABT',
    creatingAsset: 'Creando activo...',
    createAsset: 'Crear activo',
    success: 'Éxito',
    assetCreatedSuccessfully: 'Activo creado con éxito con tokens',
    error: 'Error',
    connectWalletFirst: 'Por favor, conecta tu billetera primero',
    assetCreationError: 'Error al crear el activo',
    backToDashboard: 'Volver al panel',
    loading: 'Cargando...',
    balance: 'Saldo',
    cosmoBalance: 'Saldo COSMO',
    bnbBalance: 'Saldo BNB',
    totalValue: 'Valor total',
    howToStartTitle: 'Cómo empezar',
    howToStartDescription: 'Pasos simples para comenzar a tokenizar tus activos',
    step1Title: 'Conectar billetera',
    step1Description: 'Conecta MetaMask u otra billetera compatible',
    step2Title: 'Fondear saldo',
    step2Description: 'Agrega tokens COSMO para pagar comisiones',
    step3Title: 'Crear activo',
    step3Description: 'Sube información sobre tu activo',
    step4Title: 'Comerciar tokens',
    step4Description: 'Comercia tokens en el mercado',
    aboutTitle: 'Sobre la plataforma',
    aboutDescription: 'Cosmo RWA es una plataforma revolucionaria para la tokenización de activos reales',
    missionTitle: 'Nuestra misión',
    missionDescription: 'Nos esforzamos por hacer las inversiones en activos reales accesibles para todos a través de la tecnología blockchain',
    featuresTitle: 'Nuestras características',
    feature1: 'Seguridad basada en blockchain',
    feature2: 'Accesibilidad global',
    feature3: 'Transacciones instantáneas',
    feature4: 'Comunidad de inversores',
    quickActions: 'Acciones rápidas',
    tokenizeYourAsset: 'Tokeniza tu activo',
    tradeAssetTokens: 'Comercia tokens de activos',
    loans: 'Préstamos',
    loansWithTokenCollateral: 'Préstamos con garantía de tokens',
    defiSwap: 'Intercambio DeFi',
    exchangeTokens: 'Intercambiar tokens',
    open: 'Abrir',
  },
  fr: {
    // Header
    home: 'Accueil',
    howToStart: 'Comment commencer',
    about: 'À propos',
    marketplace: 'Marché',
    dashboard: 'Tableau de bord',
    connectWallet: 'Connecter portefeuille',
    disconnect: 'Déconnecter',
    tokenizeRealAssets: 'Tokeniser',
    realAssets: 'actifs réels',
    heroSubtitle: 'Transformez l\'immobilier, les biens et autres actifs en tokens numériques avec la technologie blockchain',
    tokenLimitPerAsset: 'Limite de tokens par actif',
    stableTokens: 'Tokens stables',
    assetTrading: 'Commerce d\'actifs',
    startTokenization: 'Commencer la tokenisation',
    exploreMarketplace: 'Explorer le marché',
    highLiquidity: 'Haute liquidité',
    highLiquidityDesc: 'Échangez des actifs 24/7 sur une plateforme décentralisée',
    security: 'Sécurité',
    securityDesc: 'Protégé par la technologie blockchain et les contrats intelligents',
    tripleTokenization: 'Triple tokenisation',
    tripleTokenizationDesc: 'Tokens AST, AGT et ABT pour une flexibilité maximale',
    connectMetaMask: 'Connecter MetaMask',
    connectWalletToCreateAsset: 'Veuillez connecter votre portefeuille pour créer un actif',
    back: 'Retour',
    realEstate: 'Immobilier',
    goods: 'Biens',
    art: 'Art',
    collectibles: 'Objets de collection',
    other: 'Autre',
    assetName: "Nom de l'actif",
    assetNamePlaceholder: "Entrez le nom de l'actif",
    assetDescription: "Description de l'actif",
    assetDescriptionPlaceholder: "Exemple : Appartement au centre de Moscou, 2 pièces, 65 m²",
    assetType: "Type d'actif",
    selectAssetType: "Sélectionnez le type d'actif",
    assetValue: "Valeur de l'actif (USD)",
    location: 'Emplacement',
    locationPlaceholder: "Entrez l'emplacement",
    imageUrlOptional: "URL de l'image (optionnel)",
    tokenCalculationPreview: 'Aperçu du calcul du prix du token',
    perToken: 'par token',
    tokenLimitInfo: 'La valeur totale est répartie entre les tokens AST, AGT et ABT',
    creatingAsset: 'Création de l\'actif...',
    createAsset: 'Créer un actif',
    success: 'Succès',
    assetCreatedSuccessfully: 'Actif créé avec succès avec des tokens',
    error: 'Erreur',
    connectWalletFirst: 'Veuillez d\'abord connecter votre portefeuille',
    assetCreationError: 'Erreur lors de la création de l\'actif',
    backToDashboard: 'Retour au tableau de bord',
    loading: 'Chargement...',
    balance: 'Solde',
    cosmoBalance: 'Solde COSMO',
    bnbBalance: 'Solde BNB',
    totalValue: 'Valeur totale',
    howToStartTitle: 'Comment commencer',
    howToStartDescription: 'Étapes simples pour commencer à tokeniser vos actifs',
    step1Title: 'Connecter le portefeuille',
    step1Description: 'Connectez MetaMask ou un autre portefeuille compatible',
    step2Title: 'Alimenter le solde',
    step2Description: 'Ajoutez des tokens COSMO pour payer les frais',
    step3Title: 'Créer un actif',
    step3Description: 'Téléchargez les informations sur votre actif',
    step4Title: 'Échanger des tokens',
    step4Description: 'Échangez des tokens sur le marché',
    aboutTitle: 'À propos de la plateforme',
    aboutDescription: 'Cosmo RWA est une plateforme révolutionnaire pour la tokenisation d\'actifs réels',
    missionTitle: 'Notre mission',
    missionDescription: 'Nous nous efforçons de rendre les investissements en actifs réels accessibles à tous grâce à la technologie blockchain',
    featuresTitle: 'Nos fonctionnalités',
    feature1: 'Sécurité basée sur la blockchain',
    feature2: 'Accessibilité mondiale',
    feature3: 'Transactions instantanées',
    feature4: 'Communauté d\'investisseurs',
    quickActions: 'Actions rapides',
    tokenizeYourAsset: 'Tokenisez votre actif',
    tradeAssetTokens: 'Échangez des tokens d\'actifs',
    loans: 'Prêts',
    loansWithTokenCollateral: 'Prêts avec garantie de tokens',
    defiSwap: 'Échange DeFi',
    exchangeTokens: 'Échanger des tokens',
    open: 'Ouvrir',
  },
  de: {
    // Header
    home: 'Startseite',
    howToStart: 'Wie anfangen',
    about: 'Über uns',
    marketplace: 'Marktplatz',
    dashboard: 'Dashboard',
    connectWallet: 'Wallet verbinden',
    disconnect: 'Trennen',
    tokenizeRealAssets: 'Tokenisieren Sie',
    realAssets: 'echte Vermögenswerte',
    heroSubtitle: 'Verwandeln Sie Immobilien, Waren und andere Vermögenswerte in digitale Token mit Blockchain-Technologie',
    tokenLimitPerAsset: 'Token-Limit pro Asset',
    stableTokens: 'Stabile Token',
    assetTrading: 'Asset-Handel',
    startTokenization: 'Tokenisierung starten',
    exploreMarketplace: 'Marktplatz erkunden',
    highLiquidity: 'Hohe Liquidität',
    highLiquidityDesc: 'Handeln Sie Assets 24/7 auf einer dezentralen Plattform',
    security: 'Sicherheit',
    securityDesc: 'Geschützt durch Blockchain-Technologie und Smart Contracts',
    tripleTokenization: 'Dreifache Tokenisierung',
    tripleTokenizationDesc: 'AST-, AGT- und ABT-Token für maximale Flexibilität',
    connectMetaMask: 'MetaMask verbinden',
    connectWalletToCreateAsset: 'Bitte verbinden Sie Ihre Wallet, um ein Asset zu erstellen',
    back: 'Zurück',
    realEstate: 'Immobilien',
    goods: 'Waren',
    art: 'Kunst',
    collectibles: 'Sammlerstücke',
    other: 'Andere',
    assetName: 'Asset-Name',
    assetNamePlaceholder: 'Asset-Name eingeben',
    assetDescription: 'Asset-Beschreibung',
    assetDescriptionPlaceholder: 'Zum Beispiel: Wohnung im Zentrum von Moskau, 2 Zimmer, 65 qm',
    assetType: 'Asset-Typ',
    selectAssetType: 'Asset-Typ auswählen',
    assetValue: 'Asset-Wert (USD)',
    location: 'Standort',
    locationPlaceholder: 'Standort eingeben',
    imageUrlOptional: 'Bild-URL (optional)',
    tokenCalculationPreview: 'Vorschau der Token-Preisberechnung',
    perToken: 'pro Token',
    tokenLimitInfo: 'Der Gesamtwert wird auf die Token AST, AGT und ABT verteilt',
    creatingAsset: 'Asset wird erstellt...',
    createAsset: 'Asset erstellen',
    success: 'Erfolg',
    assetCreatedSuccessfully: 'Asset erfolgreich mit Tokens erstellt',
    error: 'Fehler',
    connectWalletFirst: 'Bitte verbinden Sie zuerst Ihre Wallet',
    assetCreationError: 'Fehler bei der Asset-Erstellung',
    backToDashboard: 'Zurück zum Dashboard',
    loading: 'Lädt...',
    balance: 'Kontostand',
    cosmoBalance: 'COSMO Kontostand',
    bnbBalance: 'BNB Kontostand',
    totalValue: 'Gesamtwert',
    howToStartTitle: 'Wie anfangen',
    howToStartDescription: 'Einfache Schritte, um mit der Tokenisierung Ihrer Assets zu beginnen',
    step1Title: 'Wallet verbinden',
    step1Description: 'Verbinden Sie MetaMask oder eine andere kompatible Wallet',
    step2Title: 'Guthaben aufladen',
    step2Description: 'Fügen Sie COSMO-Token hinzu, um Gebühren zu bezahlen',
    step3Title: 'Asset erstellen',
    step3Description: 'Laden Sie Informationen über Ihr Asset hoch',
    step4Title: 'Token handeln',
    step4Description: 'Handeln Sie Token auf dem Marktplatz',
    aboutTitle: 'Über die Plattform',
    aboutDescription: 'Cosmo RWA ist eine revolutionäre Plattform für die Tokenisierung realer Assets',
    missionTitle: 'Unsere Mission',
    missionDescription: 'Wir streben danach, Investitionen in reale Assets für alle durch Blockchain-Technologie zugänglich zu machen',
    featuresTitle: 'Unsere Funktionen',
    feature1: 'Blockchain-basierte Sicherheit',
    feature2: 'Globale Zugänglichkeit',
    feature3: 'Sofortige Transaktionen',
    feature4: 'Investoren-Community',
    quickActions: 'Schnelle Aktionen',
    tokenizeYourAsset: 'Tokenisieren Sie Ihr Asset',
    tradeAssetTokens: 'Handeln Sie Asset-Token',
    loans: 'Kredite',
    loansWithTokenCollateral: 'Kredite mit Token-Sicherheiten',
    defiSwap: 'DeFi-Tausch',
    exchangeTokens: 'Token tauschen',
    open: 'Öffnen',
  },
  zh: {
    // Header
    home: '首页',
    howToStart: '如何开始',
    about: '关于我们',
    marketplace: '市场',
    dashboard: '仪表盘',
    connectWallet: '连接钱包',
    disconnect: '断开连接',
    tokenizeRealAssets: '代币化',
    realAssets: '真实资产',
    heroSubtitle: '使用区块链技术将房地产、商品和其他资产转换为数字代币',
    tokenLimitPerAsset: '每个资产的代币限制',
    stableTokens: '稳定代币',
    assetTrading: '资产交易',
    startTokenization: '开始代币化',
    exploreMarketplace: '探索市场',
    highLiquidity: '高流动性',
    highLiquidityDesc: '在去中心化平台上24/7交易资产',
    security: '安全性',
    securityDesc: '受区块链技术和智能合约保护',
    tripleTokenization: '三重代币化',
    tripleTokenizationDesc: 'AST、AGT和ABT代币提供最大灵活性',
    connectMetaMask: '连接 MetaMask',
    connectWalletToCreateAsset: '请连接您的钱包以创建资产',
    back: '返回',
    realEstate: '房地产',
    goods: '商品',
    art: '艺术',
    collectibles: '收藏品',
    other: '其他',
    assetName: '资产名称',
    assetNamePlaceholder: '输入资产名称',
    assetDescription: '资产描述',
    assetDescriptionPlaceholder: '例如：莫斯科市中心公寓，2室，65平方米',
    assetType: '资产类型',
    selectAssetType: '选择资产类型',
    assetValue: '资产价值（美元）',
    location: '位置',
    locationPlaceholder: '输入位置',
    imageUrlOptional: '图片链接（可选）',
    tokenCalculationPreview: '代币价格计算预览',
    perToken: '每个代币',
    tokenLimitInfo: '总价值分配给 AST、AGT 和 ABT 代币',
    creatingAsset: '正在创建资产...',
    createAsset: '创建资产',
    success: '成功',
    assetCreatedSuccessfully: '资产及代币创建成功',
    error: '错误',
    connectWalletFirst: '请先连接您的钱包',
    assetCreationError: '创建资产时出错',
    backToDashboard: '返回仪表盘',
    loading: '加载中...',
    balance: '余额',
    cosmoBalance: 'COSMO 余额',
    bnbBalance: 'BNB 余额',
    totalValue: '总价值',
    howToStartTitle: '如何开始',
    howToStartDescription: '开始代币化您的资产的简单步骤',
    step1Title: '连接钱包',
    step1Description: '连接MetaMask或其他兼容钱包',
    step2Title: '充值余额',
    step2Description: '添加COSMO代币支付手续费',
    step3Title: '创建资产',
    step3Description: '上传您的资产信息',
    step4Title: '交易代币',
    step4Description: '在市场上交易代币',
    aboutTitle: '关于平台',
    aboutDescription: 'Cosmo RWA是一个革命性的真实资产代币化平台',
    missionTitle: '我们的使命',
    missionDescription: '我们努力通过区块链技术让每个人都能投资真实资产',
    featuresTitle: '我们的特色',
    feature1: '基于区块链的安全性',
    feature2: '全球可访问性',
    feature3: '即时交易',
    feature4: '投资者社区',
    quickActions: '快速操作',
    tokenizeYourAsset: '代币化您的资产',
    tradeAssetTokens: '交易资产代币',
    loans: '贷款',
    loansWithTokenCollateral: '代币抵押贷款',
    defiSwap: 'DeFi交换',
    exchangeTokens: '交换代币',
    open: '打开',
  },
  ja: {
    // Header
    home: 'ホーム',
    howToStart: '始め方',
    about: '私たちについて',
    marketplace: 'マーケットプレイス',
    dashboard: 'ダッシュボード',
    connectWallet: 'ウォレット接続',
    disconnect: '切断',
    tokenizeRealAssets: 'トークン化',
    realAssets: '実物資産',
    heroSubtitle: 'ブロックチェーン技術を使用して不動産、商品、その他の資産をデジタルトークンに変換',
    tokenLimitPerAsset: '資産あたりのトークン制限',
    stableTokens: 'ステーブルトークン',
    assetTrading: '資産取引',
    startTokenization: 'トークン化を開始',
    exploreMarketplace: 'マーケットプレイスを探索',
    highLiquidity: '高い流動性',
    highLiquidityDesc: '分散化プラットフォームで24/7資産取引',
    security: 'セキュリティ',
    securityDesc: 'ブロックチェーン技術とスマートコントラクトで保護',
    tripleTokenization: 'トリプルトークン化',
    tripleTokenizationDesc: '最大の柔軟性のためのAST、AGT、ABTトークン',
    connectMetaMask: 'MetaMaskに接続',
    connectWalletToCreateAsset: '資産を作成するにはウォレットを接続してください',
    back: '戻る',
    realEstate: '不動産',
    goods: '商品',
    art: 'アート',
    collectibles: 'コレクション',
    other: 'その他',
    assetName: '資産名',
    assetNamePlaceholder: '資産名を入力',
    assetDescription: '資産の説明',
    assetDescriptionPlaceholder: '例：モスクワ中心部のアパート、2部屋、65平方メートル',
    assetType: '資産タイプ',
    selectAssetType: '資産タイプを選択',
    assetValue: '資産価値（USD）',
    location: '場所',
    locationPlaceholder: '場所を入力',
    imageUrlOptional: '画像URL（任意）',
    tokenCalculationPreview: 'トークン価格計算プレビュー',
    perToken: 'トークンあたり',
    tokenLimitInfo: '総価値はAST、AGT、ABTトークンに分配されます',
    creatingAsset: '資産を作成中...',
    createAsset: '資産を作成',
    success: '成功',
    assetCreatedSuccessfully: 'トークン付き資産が正常に作成されました',
    error: 'エラー',
    connectWalletFirst: 'まずウォレットを接続してください',
    assetCreationError: '資産作成エラー',
    backToDashboard: 'ダッシュボードに戻る',
    loading: '読み込み中...',
    balance: '残高',
    cosmoBalance: 'COSMO残高',
    bnbBalance: 'BNB残高',
    totalValue: '総価値',
    howToStartTitle: '始め方',
    howToStartDescription: '資産のトークン化を開始するための簡単なステップ',
    step1Title: 'ウォレット接続',
    step1Description: 'MetaMaskまたは他の互換性のあるウォレットを接続',
    step2Title: '残高補充',
    step2Description: '手数料を支払うためにCOSMOトークンを追加',
    step3Title: '資産作成',
    step3Description: '資産情報をアップロード',
    step4Title: 'トークン取引',
    step4Description: 'マーケットプレイスでトークンを取引',
    aboutTitle: 'プラットフォームについて',
    aboutDescription: 'Cosmo RWAは実物資産トークン化の革命的プラットフォームです',
    missionTitle: '私たちの使命',
    missionDescription: 'ブロックチェーン技術を通じて実物資産投資を全ての人にアクセス可能にすることを目指しています',
    featuresTitle: '私たちの機能',
    feature1: 'ブロックチェーンベースのセキュリティ',
    feature2: 'グローバルなアクセシビリティ',
    feature3: '即座の取引',
    feature4: '投資家コミュニティ',
    quickActions: 'クイックアクション',
    tokenizeYourAsset: '資産をトークン化',
    tradeAssetTokens: '資産トークンを取引',
    loans: 'ローン',
    loansWithTokenCollateral: 'トークン担保ローン',
    defiSwap: 'DeFiスワップ',
    exchangeTokens: 'トークン交換',
    open: '開く',
  },
  ar: {
    // Header
    home: 'الرئيسية',
    howToStart: 'كيفية البدء',
    about: 'حول',
    marketplace: 'السوق',
    dashboard: 'لوحة التحكم',
    connectWallet: 'ربط المحفظة',
    disconnect: 'قطع الاتصال',
    tokenizeRealAssets: 'رمز',
    realAssets: 'الأصول الحقيقية',
    heroSubtitle: 'حول العقارات والسلع والأصول الأخرى إلى رموز رقمية باستخدام تقنية البلوك تشين',
    tokenLimitPerAsset: 'حد الرموز لكل أصل',
    stableTokens: 'رموز مستقرة',
    assetTrading: 'تداول الأصول',
    startTokenization: 'بدء الترميز',
    exploreMarketplace: 'استكشاف السوق',
    highLiquidity: 'سيولة عالية',
    highLiquidityDesc: 'تداول الأصول 24/7 على منصة لامركزية',
    security: 'الأمان',
    securityDesc: 'محمي بتقنية البلوك تشين والعقود الذكية',
    tripleTokenization: 'ترميز ثلاثي',
    tripleTokenizationDesc: 'رموز AST و AGT و ABT لأقصى مرونة',
    connectMetaMask: 'اتصل بـ MetaMask',
    connectWalletToCreateAsset: 'يرجى توصيل محفظتك لإنشاء أصل',
    back: 'عودة',
    realEstate: 'عقارات',
    goods: 'سلع',
    art: 'فن',
    collectibles: 'مقتنيات',
    other: 'أخرى',
    assetName: 'اسم الأصل',
    assetNamePlaceholder: 'أدخل اسم الأصل',
    assetDescription: 'وصف الأصل',
    assetDescriptionPlaceholder: 'مثال: شقة في وسط موسكو، غرفتان، 65 متر مربع',
    assetType: 'نوع الأصل',
    selectAssetType: 'اختر نوع الأصل',
    assetValue: 'قيمة الأصل (دولار أمريكي)',
    location: 'الموقع',
    locationPlaceholder: 'أدخل الموقع',
    imageUrlOptional: 'رابط الصورة (اختياري)',
    tokenCalculationPreview: 'معاينة حساب سعر التوكن',
    perToken: 'لكل توكن',
    tokenLimitInfo: 'يتم توزيع القيمة الإجمالية بين توكنات AST و AGT و ABT',
    creatingAsset: 'جارٍ إنشاء الأصل...',
    createAsset: 'إنشاء أصل',
    success: 'نجاح',
    assetCreatedSuccessfully: 'تم إنشاء الأصل بنجاح مع التوكنات',
    error: 'خطأ',
    connectWalletFirst: 'يرجى توصيل محفظتك أولاً',
    assetCreationError: 'خطأ في إنشاء الأصل',
    backToDashboard: 'العودة إلى لوحة التحكم',
    loading: 'جارٍ التحميل...',
    balance: 'الرصيد',
    cosmoBalance: 'رصيد COSMO',
    bnbBalance: 'رصيد BNB',
    totalValue: 'القيمة الإجمالية',
    howToStartTitle: 'كيفية البدء',
    howToStartDescription: 'خطوات بسيطة لبدء ترميز أصولك',
    step1Title: 'ربط المحفظة',
    step1Description: 'اربط MetaMask أو محفظة أخرى متوافقة',
    step2Title: 'تمويل الرصيد',
    step2Description: 'أضف رموز COSMO لدفع الرسوم',
    step3Title: 'إنشاء أصل',
    step3Description: 'ارفع معلومات أصلك',
    step4Title: 'تداول الرموز',
    step4Description: 'تداول الرموز في السوق',
    aboutTitle: 'حول المنصة',
    aboutDescription: 'Cosmo RWA هي منصة ثورية لترميز الأصول الحقيقية',
    missionTitle: 'مهمتنا',
    missionDescription: 'نسعى لجعل الاستثمار في الأصول الحقيقية متاحاً للجميع من خلال تقنية البلوك تشين',
    featuresTitle: 'ميزاتنا',
    feature1: 'أمان قائم على البلوك تشين',
    feature2: 'امكانية الوصول العالمي',
    feature3: 'معاملات فورية',
    feature4: 'مجتمع المستثمرين',
    quickActions: 'إجراءات سريعة',
    tokenizeYourAsset: 'رمز أصلك',
    tradeAssetTokens: 'تداول رموز الأصول',
    loans: 'القروض',
    loansWithTokenCollateral: 'قروض بضمان الرموز',
    defiSwap: 'تبديل DeFi',
    exchangeTokens: 'تبديل الرموز',
    open: 'فتح',
  },
  pt: {
    // Header
    home: 'Início',
    howToStart: 'Como começar',
    about: 'Sobre',
    marketplace: 'Mercado',
    dashboard: 'Painel',
    connectWallet: 'Conectar carteira',
    disconnect: 'Desconectar',
    tokenizeRealAssets: 'Tokenizar',
    realAssets: 'ativos reais',
    heroSubtitle: 'Transforme imóveis, mercadorias e outros ativos em tokens digitais usando tecnologia blockchain',
    tokenLimitPerAsset: 'Limite de tokens por ativo',
    stableTokens: 'Tokens estáveis',
    assetTrading: 'Negociação de ativos',
    startTokenization: 'Iniciar tokenização',
    exploreMarketplace: 'Explorar mercado',
    highLiquidity: 'Alta liquidez',
    highLiquidityDesc: 'Negocie ativos 24/7 em uma plataforma descentralizada',
    security: 'Segurança',
    securityDesc: 'Protegido por tecnologia blockchain e contratos inteligentes',
    tripleTokenization: 'Tokenização tripla',
    tripleTokenizationDesc: 'Tokens AST, AGT e ABT para máxima flexibilidade',
    connectMetaMask: 'Conectar MetaMask',
    connectWalletToCreateAsset: 'Por favor, conecte sua carteira para criar um ativo',
    back: 'Voltar',
    realEstate: 'Imóveis',
    goods: 'Bens',
    art: 'Arte',
    collectibles: 'Colecionáveis',
    other: 'Outro',
    assetName: 'Nome do ativo',
    assetNamePlaceholder: 'Digite o nome do ativo',
    assetDescription: 'Descrição do ativo',
    assetDescriptionPlaceholder: 'Exemplo: Apartamento no centro de Moscou, 2 quartos, 65 m²',
    assetType: 'Tipo de ativo',
    selectAssetType: 'Selecione o tipo de ativo',
    assetValue: 'Valor do ativo (USD)',
    location: 'Localização',
    locationPlaceholder: 'Digite a localização',
    imageUrlOptional: 'URL da imagem (opcional)',
    tokenCalculationPreview: 'Prévia do cálculo do preço do token',
    perToken: 'por token',
    tokenLimitInfo: 'O valor total é distribuído entre os tokens AST, AGT e ABT',
    creatingAsset: 'Criando ativo...',
    createAsset: 'Criar ativo',
    success: 'Sucesso',
    assetCreatedSuccessfully: 'Ativo criado com sucesso com tokens',
    error: 'Erro',
    connectWalletFirst: 'Por favor, conecte sua carteira primeiro',
    assetCreationError: 'Erro ao criar ativo',
    backToDashboard: 'Voltar ao painel',
    loading: 'Carregando...',
    balance: 'Saldo',
    cosmoBalance: 'Saldo COSMO',
    bnbBalance: 'Saldo BNB',
    totalValue: 'Valor total',
    howToStartTitle: 'Como começar',
    howToStartDescription: 'Passos simples para começar a tokenizar seus ativos',
    step1Title: 'Conectar carteira',
    step1Description: 'Conecte MetaMask ou outra carteira compatível',
    step2Title: 'Financiar saldo',
    step2Description: 'Adicione tokens COSMO para pagar taxas',
    step3Title: 'Criar ativo',
    step3Description: 'Faça upload das informações do seu ativo',
    step4Title: 'Negociar tokens',
    step4Description: 'Negocie tokens no mercado',
    aboutTitle: 'Sobre a plataforma',
    aboutDescription: 'Cosmo RWA é uma plataforma revolucionária para tokenização de ativos reais',
    missionTitle: 'Nossa missão',
    missionDescription: 'Nos esforçamos para tornar os investimentos em ativos reais acessíveis a todos através da tecnologia blockchain',
    featuresTitle: 'Nossas funcionalidades',
    feature1: 'Segurança baseada em blockchain',
    feature2: 'Acessibilidade global',
    feature3: 'Transações instantâneas',
    feature4: 'Comunidade de investidores',
    quickActions: 'Ações rápidas',
    tokenizeYourAsset: 'Tokenize seu ativo',
    tradeAssetTokens: 'Negocie tokens de ativos',
    loans: 'Empréstimos',
    loansWithTokenCollateral: 'Empréstimos com garantia de tokens',
    defiSwap: 'Swap DeFi',
    exchangeTokens: 'Trocar tokens',
    open: 'Abrir',
  },
  hi: {
    // Header
    home: 'होम',
    howToStart: 'कैसे शुरू करें',
    about: 'हमारे बारे में',
    marketplace: 'बाज़ार',
    dashboard: 'डैशबोर्ड',
    connectWallet: 'वॉलेट कनेक्ट करें',
    disconnect: 'डिस्कनेक्ट करें',
    tokenizeRealAssets: 'टोकनाइज़ करें',
    realAssets: 'वास्तविक संपत्ति',
    heroSubtitle: 'ब्लॉकचेन तकनीक का उपयोग करके रियल एस्टेट, सामान और अन्य संपत्तियों को डिजिटल टोकन में बदलें',
    tokenLimitPerAsset: 'प्रति संपत्ति टोकन सीमा',
    stableTokens: 'स्थिर टोकन',
    assetTrading: 'संपत्ति व्यापार',
    startTokenization: 'टोकनाइज़ेशन शुरू करें',
    exploreMarketplace: 'बाज़ार देखें',
    highLiquidity: 'उच्च तरलता',
    highLiquidityDesc: 'विकेंद्रीकृत प्लेटफॉर्म पर 24/7 संपत्तियों का व्यापार करें',
    security: 'सुरक्षा',
    securityDesc: 'ब्लॉकचेन तकनीक और स्मार्ट कॉन्ट्रैक्ट्स द्वारा संरक्षित',
    tripleTokenization: 'ट्रिपल टोकनाइज़ेशन',
    tripleTokenizationDesc: 'अधिकतम लचीलेपन के लिए AST, AGT और ABT टोकन',
    connectMetaMask: 'MetaMask से कनेक्ट करें',
    connectWalletToCreateAsset: 'कृपया एक संपत्ति बनाने के लिए अपना वॉलेट कनेक्ट करें',
    back: 'वापस',
    realEstate: 'अचल संपत्ति',
    goods: 'सामान',
    art: 'कला',
    collectibles: 'संग्रहणीय वस्तुएं',
    other: 'अन्य',
    assetName: 'संपत्ति का नाम',
    assetNamePlaceholder: 'संपत्ति का नाम दर्ज करें',
    assetDescription: 'संपत्ति का विवरण',
    assetDescriptionPlaceholder: 'उदाहरण: मॉस्को के केंद्र में अपार्टमेंट, 2 कमरे, 65 वर्ग मीटर',
    assetType: 'संपत्ति का प्रकार',
    selectAssetType: 'संपत्ति का प्रकार चुनें',
    assetValue: 'संपत्ति का मूल्य (USD)',
    location: 'स्थान',
    locationPlaceholder: 'स्थान दर्ज करें',
    imageUrlOptional: 'छवि URL (वैकल्पिक)',
    tokenCalculationPreview: 'टोकन मूल्य गणना पूर्वावलोकन',
    perToken: 'प्रति टोकन',
    tokenLimitInfo: 'कुल मूल्य AST, AGT, और ABT टोकन में वितरित किया जाता है',
    creatingAsset: 'संपत्ति बनाई जा रही है...',
    createAsset: 'संपत्ति बनाएं',
    success: 'सफलता',
    assetCreatedSuccessfully: 'टोकन के साथ संपत्ति सफलतापूर्वक बनाई गई',
    error: 'त्रुटि',
    connectWalletFirst: 'कृपया पहले अपना वॉलेट कनेक्ट करें',
    assetCreationError: 'संपत्ति बनाने में त्रुटि',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    loading: 'लोड हो रहा है...',
    balance: 'बैलेंस',
    cosmoBalance: 'COSMO बैलेंस',
    bnbBalance: 'BNB बैलेंस',
    totalValue: 'कुल मूल्य',
    howToStartTitle: 'कैसे शुरू करें',
    howToStartDescription: 'अपनी संपत्तियों को टोकनाइज़ करने के लिए सरल चरण',
    step1Title: 'वॉलेट कनेक्ट करें',
    step1Description: 'MetaMask या अन्य संगत वॉलेट कनेक्ट करें',
    step2Title: 'बैलेंस फंड करें',
    step2Description: 'फीस भुगतान के लिए COSMO टोकन जोड़ें',
    step3Title: 'संपत्ति बनाएं',
    step3Description: 'अपनी संपत्ति की जानकारी अपलोड करें',
    step4Title: 'टोकन ट्रेड करें',
    step4Description: 'बाज़ार में टोकन का व्यापार करें',
    aboutTitle: 'प्लेटफॉर्म के बारे में',
    aboutDescription: 'Cosmo RWA वास्तविक संपत्ति टोकनाइज़ेशन के लिए एक क्रांतिकारी प्लेटफॉर्म है',
    missionTitle: 'हमारा मिशन',
    missionDescription: 'हम ब्लॉकचेन तकनीक के माध्यम से वास्तविक संपत्ति निवेश को सभी के लिए सुलभ बनाने का प्रयास करते हैं',
    featuresTitle: 'हमारी विशेषताएं',
    feature1: 'ब्लॉकचेन-आधारित सुरक्षा',
    feature2: 'वैश्विक पहुंच',
    feature3: 'तत्काल लेनदेन',
    feature4: 'निवेशक समुदाय',
    quickActions: 'त्वरित क्रियाएं',
    tokenizeYourAsset: 'अपनी संपत्ति को टोकनाइज़ करें',
    tradeAssetTokens: 'संपत्ति टोकन का व्यापार करें',
    loans: 'ऋण',
    loansWithTokenCollateral: 'टोकन जमानत के साथ ऋण',
    defiSwap: 'DeFi स्वैप',
    exchangeTokens: 'टोकन एक्सचेंज करें',
    open: 'खोलें',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
