import { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Полные словари переводов для 10 языков
const translations = {
  ru: {
    // Общие
    'welcome': 'Добро пожаловать',
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'success': 'Успешно',
    'cancel': 'Отмена',
    'confirm': 'Подтвердить',
    'back': 'Назад',
    'next': 'Далее',
    'save': 'Сохранить',
    'edit': 'Редактировать',
    'delete': 'Удалить',
    'open': 'Открыть',
    
    // Навигация
    'home': 'Главная',
    'marketplace': 'Маркетплейс',
    'dashboard': 'Личный кабинет',
    'howToStart': 'Как начать',
    'about': 'О проекте',
    'connectWallet': 'Подключить кошелек',
    'disconnect': 'Отключить',
    
    // Hero секция
    'tokenizeRealAssets': 'Токенизируйте',
    'realAssets': 'реальные активы',
    'heroSubtitle': 'Cosmo RWA — первая децентрализованная платформа для токенизации недвижимости, товаров и других активов с автоматическим созданием трех уникальных токенов',
    'tokenLimitPerAsset': 'Лимит токенов на актив',
    'stableTokens': 'Стабильные токены (AST)',
    'assetTrading': 'Торговля активами',
    'startTokenization': 'Начать токенизацию',
    'exploreMarketplace': 'Изучить маркетплейс',
    'highLiquidity': 'Высокая ликвидность',
    'highLiquidityDesc': 'Создавайте пулы ликвидности для всех трех типов токенов',
    'security': 'Безопасность',
    'securityDesc': 'Смарт-контракты обеспечивают прозрачность и безопасность сделок',
    'tripleTokenization': 'Тройная токенизация',
    'tripleTokenizationDesc': 'Стабильные (90%), поддержки (9%) и брендовые (1%) токены',
    
    // Аутентификация
    'connectMetaMask': 'Подключить MetaMask',
    'connectingWallet': 'Подключение кошелька...',
    'walletConnected': 'Кошелек подключен',
    'walletConnectionError': 'Ошибка подключения кошелька',
    'installMetaMask': 'Установите MetaMask',
    'switchToCorrectNetwork': 'Переключите на BNB Smart Chain',
    'connectWalletToCreateAsset': 'Подключите кошелек для создания актива',
    'connectWalletFirst': 'Сначала подключите кошелек',
    
    // Токены
    'buyCosmoCoin': 'Купить токен COSMO',
    'buyCosmoCoinDescription': 'Покупайте токены COSMO на PancakeSwap для использования в платформе',
    'tokenContract': 'Контракт токена',
    'network': 'Сеть',
    'exchange': 'Биржа',
    'buyOnPancakeSwap': 'Купить на PancakeSwap',
    'opening': 'Открывается...',
    'pancakeSwapWarning': 'Вы будете перенаправлены на PancakeSwap. Убедитесь, что используете правильный контракт токена.',
    'tokens': 'Токены',
    'defiSwap': 'DeFi Обмен',
    'exchangeTokens': 'Обменивайте токены',
    'perToken': 'за токен',
    
    // Баланс
    'balance': 'Баланс',
    'cosmoBalance': 'Баланс COSMO',
    'bnbBalance': 'Баланс BNB',
    'totalValue': 'Общая стоимость',
    'totalRevenue': 'Общий доход',
    
    // Активы
    'createAsset': 'Создать актив',
    'myAssets': 'Мои активы',
    'assetName': 'Название актива',
    'assetDescription': 'Описание актива',
    'assetType': 'Тип актива',
    'assetValue': 'Стоимость (USD)',
    'location': 'Локация',
    'realEstate': 'Недвижимость',
    'goods': 'Товары',
    'art': 'Искусство',
    'collectibles': 'Коллекционные предметы',
    'other': 'Другое',
    'tokenizeYourAsset': 'Токенизируйте свой актив',
    'tradeAssetTokens': 'Торгуйте токенами активов',
    'loansWithTokenCollateral': 'Займы под залог токенов',
    'quickActions': 'Быстрые действия',
    'assetTokenization': 'Токенизация актива',
    'assetTokenizationDescription': 'Создайте три уникальных токена для вашего актива: AST (90%), AGT (9%), ABT (1%)',
    'assetNamePlaceholder': 'Например: Квартира в центре Москвы',
    'assetDescriptionPlaceholder': 'Подробное описание актива...',
    'selectAssetType': 'Выберите тип актива',
    'locationPlaceholder': 'Москва, Россия',
    'imageUrlOptional': 'URL изображения (опционально)',
    'tokenCalculationPreview': 'Предварительный расчет токенов',
    'tokenLimitInfo': 'Лимит каждого токена: 1,000,000,000 штук',
    'creatingAsset': 'Создание актива...',
    'assetCreatedSuccessfully': 'Актив создан успешно! Созданы токены',
    'assetCreationError': 'Ошибка создания актива',
    'backToDashboard': 'В личный кабинет',
    
    // Транзакции
    'transactions': 'Транзакции',
    'transactionHistory': 'История транзакций',
    'buy': 'Купить',
    'sell': 'Продать',
    'collateral': 'Заложить',
    'liquidity': 'Ликвидность',
    
    // Кредиты
    'loans': 'Кредиты',
    'borrow': 'Занять',
    'lend': 'Дать в долг',
    'loanAmount': 'Сумма кредита',
    'interestRate': 'Процентная ставка',
    'duration': 'Срок',
    'collateralAmount': 'Сумма залога',
    
    // Как начать
    'howToStartTitle': 'Как начать работу с Cosmo RWA',
    'howToStartDescription': 'Следуйте этим простым шагам, чтобы начать токенизацию ваших активов',
    'step1Title': 'Подключите MetaMask',
    'step1Description': 'Установите и настройте кошелек MetaMask для работы с BNB Smart Chain',
    'step2Title': 'Купите токены COSMO',
    'step2Description': 'Приобретите токены COSMO на PancakeSwap для использования в платформе',
    'step3Title': 'Создайте актив',
    'step3Description': 'Токенизируйте свой актив и получите три уникальных токена',
    'step4Title': 'Торгуйте на маркетплейсе',
    'step4Description': 'Покупайте и продавайте токены активов на нашем маркетплейсе',
    
    // О проекте
    'aboutTitle': 'О проекте Cosmo RWA',
    'aboutDescription': 'Cosmo RWA - это инновационная децентрализованная платформа для токенизации реальных активов на блокчейне BNB Smart Chain.',
    'missionTitle': 'Наша миссия',
    'missionDescription': 'Мы делаем инвестиции в реальные активы доступными для всех через технологию блокчейна.',
    'featuresTitle': 'Особенности платформы',
    'feature1': 'Автоматическое создание трех типов токенов для каждого актива',
    'feature2': 'Децентрализованная торговля и обмен токенами',
    'feature3': 'Кредитование под залог токенизированных активов',
    'feature4': 'Прозрачность и безопасность блокчейна'
  },
  
  en: {
    // General
    'welcome': 'Welcome',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'back': 'Back',
    'next': 'Next',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'open': 'Open',
    
    // Navigation
    'home': 'Home',
    'marketplace': 'Marketplace',
    'dashboard': 'Dashboard',
    'howToStart': 'How to Start',
    'about': 'About',
    'connectWallet': 'Connect Wallet',
    'disconnect': 'Disconnect',
    
    // Hero section
    'tokenizeRealAssets': 'Tokenize',
    'realAssets': 'real assets',
    'heroSubtitle': 'Cosmo RWA — the first decentralized platform for tokenizing real estate, goods and other assets with automatic creation of three unique tokens',
    'tokenLimitPerAsset': 'Token limit per asset',
    'stableTokens': 'Stable tokens (AST)',
    'assetTrading': 'Asset trading',
    'startTokenization': 'Start Tokenization',
    'exploreMarketplace': 'Explore Marketplace',
    'highLiquidity': 'High Liquidity',
    'highLiquidityDesc': 'Create liquidity pools for all three token types',
    'security': 'Security',
    'securityDesc': 'Smart contracts ensure transparency and security of transactions',
    'tripleTokenization': 'Triple Tokenization',
    'tripleTokenizationDesc': 'Stable (90%), support (9%) and brand (1%) tokens',
    
    // Authentication
    'connectMetaMask': 'Connect MetaMask',
    'connectingWallet': 'Connecting wallet...',
    'walletConnected': 'Wallet connected',
    'walletConnectionError': 'Wallet connection error',
    'installMetaMask': 'Install MetaMask',
    'switchToCorrectNetwork': 'Switch to BNB Smart Chain',
    'connectWalletToCreateAsset': 'Connect wallet to create asset',
    'connectWalletFirst': 'Connect wallet first',
    
    // Tokens
    'buyCosmoCoin': 'Buy COSMO Token',
    'buyCosmoCoinDescription': 'Purchase COSMO tokens on PancakeSwap to use in the platform',
    'tokenContract': 'Token Contract',
    'network': 'Network',
    'exchange': 'Exchange',
    'buyOnPancakeSwap': 'Buy on PancakeSwap',
    'opening': 'Opening...',
    'pancakeSwapWarning': 'You will be redirected to PancakeSwap. Make sure to use the correct token contract.',
    'tokens': 'Tokens',
    'defiSwap': 'DeFi Swap',
    'exchangeTokens': 'Exchange tokens',
    'perToken': 'per token',
    
    // Balance
    'balance': 'Balance',
    'cosmoBalance': 'COSMO Balance',
    'bnbBalance': 'BNB Balance',
    'totalValue': 'Total Value',
    'totalRevenue': 'Total Revenue',
    
    // Assets
    'createAsset': 'Create Asset',
    'myAssets': 'My Assets',
    'assetName': 'Asset Name',
    'assetDescription': 'Asset Description',
    'assetType': 'Asset Type',
    'assetValue': 'Value (USD)',
    'location': 'Location',
    'realEstate': 'Real Estate',
    'goods': 'Goods',
    'art': 'Art',
    'collectibles': 'Collectibles',
    'other': 'Other',
    'tokenizeYourAsset': 'Tokenize your asset',
    'tradeAssetTokens': 'Trade asset tokens',
    'loansWithTokenCollateral': 'Loans with token collateral',
    'quickActions': 'Quick Actions',
    'assetTokenization': 'Asset Tokenization',
    'assetTokenizationDescription': 'Create three unique tokens for your asset: AST (90%), AGT (9%), ABT (1%)',
    'assetNamePlaceholder': 'e.g: Apartment in city center',
    'assetDescriptionPlaceholder': 'Detailed asset description...',
    'selectAssetType': 'Select asset type',
    'locationPlaceholder': 'New York, USA',
    'imageUrlOptional': 'Image URL (optional)',
    'tokenCalculationPreview': 'Token calculation preview',
    'tokenLimitInfo': 'Limit of each token: 1,000,000,000 pieces',
    'creatingAsset': 'Creating asset...',
    'assetCreatedSuccessfully': 'Asset created successfully! Created tokens',
    'assetCreationError': 'Asset creation error',
    'backToDashboard': 'Back to Dashboard',
    
    // Transactions
    'transactions': 'Transactions',
    'transactionHistory': 'Transaction History',
    'buy': 'Buy',
    'sell': 'Sell',
    'collateral': 'Collateral',
    'liquidity': 'Liquidity',
    
    // Loans
    'loans': 'Loans',
    'borrow': 'Borrow',
    'lend': 'Lend',
    'loanAmount': 'Loan Amount',
    'interestRate': 'Interest Rate',
    'duration': 'Duration',
    'collateralAmount': 'Collateral Amount',
    
    // How to start
    'howToStartTitle': 'How to Get Started with Cosmo RWA',
    'howToStartDescription': 'Follow these simple steps to start tokenizing your assets',
    'step1Title': 'Connect MetaMask',
    'step1Description': 'Install and configure MetaMask wallet for BNB Smart Chain',
    'step2Title': 'Buy COSMO Tokens',
    'step2Description': 'Purchase COSMO tokens on PancakeSwap to use in the platform',
    'step3Title': 'Create Asset',
    'step3Description': 'Tokenize your asset and receive three unique tokens',
    'step4Title': 'Trade on Marketplace',
    'step4Description': 'Buy and sell asset tokens on our marketplace',
    
    // About
    'aboutTitle': 'About Cosmo RWA Project',
    'aboutDescription': 'Cosmo RWA is an innovative decentralized platform for tokenizing real-world assets on the BNB Smart Chain.',
    'missionTitle': 'Our Mission',
    'missionDescription': 'We make real asset investments accessible to everyone through blockchain technology.',
    'featuresTitle': 'Platform Features',
    'feature1': 'Automatic creation of three token types for each asset',
    'feature2': 'Decentralized trading and token exchange',
    'feature3': 'Lending with tokenized asset collateral',
    'feature4': 'Blockchain transparency and security'
  },
  
  es: {
    'welcome': 'Bienvenido',
    'loading': 'Cargando...',
    'error': 'Error',
    'success': 'Éxito',
    'open': 'Abrir',
    'home': 'Inicio',
    'marketplace': 'Mercado',
    'dashboard': 'Panel',
    'howToStart': 'Cómo Empezar',
    'about': 'Acerca de',
    'connectMetaMask': 'Conectar MetaMask',
    'balance': 'Balance',
    'createAsset': 'Crear Activo',
    'startTokenization': 'Iniciar Tokenización',
    'tokenizeRealAssets': 'Tokenizar',
    'realAssets': 'activos reales',
    'heroSubtitle': 'Cosmo RWA — la primera plataforma descentralizada para tokenizar bienes raíces, mercancías y otros activos',
    'exploreMarketplace': 'Explorar Mercado',
    'highLiquidity': 'Alta Liquidez',
    'security': 'Seguridad',
    'tripleTokenization': 'Triple Tokenización',
    'tokens': 'Tokens',
    'myAssets': 'Mis Activos',
    'transactions': 'Transacciones',
    'totalRevenue': 'Ingresos Totales',
    'quickActions': 'Acciones Rápidas',
    'tokenizeYourAsset': 'Tokenizar activo',
    'tradeAssetTokens': 'Comerciar tokens',
    'loansWithTokenCollateral': 'Préstamos con garantía',
    'defiSwap': 'DeFi Intercambio',
    'exchangeTokens': 'Intercambiar tokens',
    'loans': 'Préstamos',
    'disconnect': 'Desconectar',
    'connectingWallet': 'Conectando cartera...',
    'cosmoBalance': 'Balance COSMO',
    'bnbBalance': 'Balance BNB',
    'totalValue': 'Valor Total',
    'perToken': 'por token'
  },
  
  fr: {
    'welcome': 'Bienvenue',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'success': 'Succès',
    'open': 'Ouvrir',
    'home': 'Accueil',
    'marketplace': 'Marché',
    'dashboard': 'Tableau de bord',
    'howToStart': 'Comment Commencer',
    'about': 'À propos',
    'connectMetaMask': 'Connecter MetaMask',
    'balance': 'Solde',
    'createAsset': 'Créer un Actif',
    'startTokenization': 'Commencer la Tokenisation',
    'tokenizeRealAssets': 'Tokeniser',
    'realAssets': 'actifs réels',
    'heroSubtitle': 'Cosmo RWA — la première plateforme décentralisée pour tokeniser l\'immobilier, les biens et autres actifs',
    'exploreMarketplace': 'Explorer le Marché',
    'highLiquidity': 'Haute Liquidité',
    'security': 'Sécurité',
    'tripleTokenization': 'Triple Tokenisation',
    'tokens': 'Jetons',
    'myAssets': 'Mes Actifs',
    'transactions': 'Transactions',
    'totalRevenue': 'Revenus Totaux',
    'quickActions': 'Actions Rapides',
    'tokenizeYourAsset': 'Tokeniser votre actif',
    'tradeAssetTokens': 'Échanger des jetons',
    'loansWithTokenCollateral': 'Prêts avec garantie',
    'defiSwap': 'DeFi Échange',
    'exchangeTokens': 'Échanger des jetons',
    'loans': 'Prêts',
    'disconnect': 'Déconnecter',
    'connectingWallet': 'Connexion portefeuille...',
    'cosmoBalance': 'Solde COSMO',
    'bnbBalance': 'Solde BNB',
    'totalValue': 'Valeur Totale',
    'perToken': 'par jeton'
  },
  
  de: {
    'welcome': 'Willkommen',
    'loading': 'Laden...',
    'error': 'Fehler',
    'success': 'Erfolg',
    'open': 'Öffnen',
    'home': 'Startseite',
    'marketplace': 'Marktplatz',
    'dashboard': 'Dashboard',
    'howToStart': 'Wie Anfangen',
    'about': 'Über uns',
    'connectMetaMask': 'MetaMask Verbinden',
    'balance': 'Guthaben',
    'createAsset': 'Asset Erstellen',
    'startTokenization': 'Tokenisierung Starten',
    'tokenizeRealAssets': 'Tokenisieren',
    'realAssets': 'reale Vermögenswerte',
    'heroSubtitle': 'Cosmo RWA — die erste dezentralisierte Plattform zur Tokenisierung von Immobilien, Waren und anderen Vermögenswerten',
    'exploreMarketplace': 'Marktplatz Erkunden',
    'highLiquidity': 'Hohe Liquidität',
    'security': 'Sicherheit',
    'tripleTokenization': 'Dreifache Tokenisierung',
    'tokens': 'Token',
    'myAssets': 'Meine Assets',
    'transactions': 'Transaktionen',
    'totalRevenue': 'Gesamtumsatz',
    'quickActions': 'Schnelle Aktionen',
    'tokenizeYourAsset': 'Asset tokenisieren',
    'tradeAssetTokens': 'Token handeln',
    'loansWithTokenCollateral': 'Kredite mit Sicherheit',
    'defiSwap': 'DeFi Tausch',
    'exchangeTokens': 'Token tauschen',
    'loans': 'Kredite',
    'disconnect': 'Trennen',
    'connectingWallet': 'Wallet verbinden...',
    'cosmoBalance': 'COSMO Guthaben',
    'bnbBalance': 'BNB Guthaben',
    'totalValue': 'Gesamtwert',
    'perToken': 'pro Token'
  },
  
  zh: {
    'welcome': '欢迎',
    'loading': '加载中...',
    'error': '错误',
    'success': '成功',
    'open': '打开',
    'home': '首页',
    'marketplace': '市场',
    'dashboard': '仪表板',
    'howToStart': '如何开始',
    'about': '关于我们',
    'connectMetaMask': '连接MetaMask',
    'balance': '余额',
    'createAsset': '创建资产',
    'startTokenization': '开始代币化',
    'tokenizeRealAssets': '代币化',
    'realAssets': '真实资产',
    'heroSubtitle': 'Cosmo RWA — 第一个用于房地产、商品和其他资产代币化的去中心化平台',
    'exploreMarketplace': '探索市场',
    'highLiquidity': '高流动性',
    'security': '安全性',
    'tripleTokenization': '三重代币化',
    'tokens': '代币',
    'myAssets': '我的资产',
    'transactions': '交易',
    'totalRevenue': '总收入',
    'quickActions': '快捷操作',
    'tokenizeYourAsset': '代币化资产',
    'tradeAssetTokens': '交易代币',
    'loansWithTokenCollateral': '抵押贷款',
    'defiSwap': 'DeFi交换',
    'exchangeTokens': '交换代币',
    'loans': '贷款',
    'disconnect': '断开',
    'connectingWallet': '连接钱包...',
    'cosmoBalance': 'COSMO余额',
    'bnbBalance': 'BNB余额',
    'totalValue': '总价值',
    'perToken': '每代币'
  },
  
  ja: {
    'welcome': 'ようこそ',
    'loading': '読み込み中...',
    'error': 'エラー',
    'success': '成功',
    'open': '開く',
    'home': 'ホーム',
    'marketplace': 'マーケット',
    'dashboard': 'ダッシュボード',
    'howToStart': '始め方',
    'about': '私たちについて',
    'connectMetaMask': 'MetaMaskに接続',
    'balance': '残高',
    'createAsset': 'アセット作成',
    'startTokenization': 'トークン化開始',
    'tokenizeRealAssets': 'トークン化',
    'realAssets': 'リアルアセット',
    'heroSubtitle': 'Cosmo RWA — 不動産、商品、その他の資産をトークン化する最初の分散型プラットフォーム',
    'exploreMarketplace': 'マーケットを探索',
    'highLiquidity': '高い流動性',
    'security': 'セキュリティ',
    'tripleTokenization': 'トリプルトークン化',
    'tokens': 'トークン',
    'myAssets': 'マイアセット',
    'transactions': '取引',
    'totalRevenue': '総収益',
    'quickActions': 'クイックアクション',
    'tokenizeYourAsset': 'アセットをトークン化',
    'tradeAssetTokens': 'トークンを取引',
    'loansWithTokenCollateral': '担保付きローン',
    'defiSwap': 'DeFiスワップ',
    'exchangeTokens': 'トークン交換',
    'loans': 'ローン',
    'disconnect': '切断',
    'connectingWallet': 'ウォレット接続中...',
    'cosmoBalance': 'COSMO残高',
    'bnbBalance': 'BNB残高',
    'totalValue': '総価値',
    'perToken': 'トークンあたり'
  },
  
  ar: {
    'welcome': 'مرحبا',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'نجح',
    'open': 'فتح',
    'home': 'الرئيسية',
    'marketplace': 'السوق',
    'dashboard': 'لوحة القيادة',
    'howToStart': 'كيفية البدء',
    'about': 'حولنا',
    'connectMetaMask': 'ربط MetaMask',
    'balance': 'الرصيد',
    'createAsset': 'إنشاء أصل',
    'startTokenization': 'بدء الترميز',
    'tokenizeRealAssets': 'ترميز',
    'realAssets': 'الأصول الحقيقية',
    'heroSubtitle': 'Cosmo RWA — أول منصة لامركزية لترميز العقارات والسلع والأصول الأخرى',
    'exploreMarketplace': 'استكشاف السوق',
    'highLiquidity': 'سيولة عالية',
    'security': 'الأمان',
    'tripleTokenization': 'ترميز ثلاثي',
    'tokens': 'الرموز',
    'myAssets': 'أصولي',
    'transactions': 'المعاملات',
    'totalRevenue': 'إجمالي الإيرادات',
    'quickActions': 'إجراءات سريعة',
    'tokenizeYourAsset': 'رمز أصلك',
    'tradeAssetTokens': 'تداول الرموز',
    'loansWithTokenCollateral': 'قروض بضمانة',
    'defiSwap': 'DeFi تبادل',
    'exchangeTokens': 'تبادل الرموز',
    'loans': 'قروض',
    'disconnect': 'قطع الاتصال',
    'connectingWallet': 'ربط المحفظة...',
    'cosmoBalance': 'رصيد COSMO',
    'bnbBalance': 'رصيد BNB',
    'totalValue': 'القيمة الإجمالية',
    'perToken': 'لكل رمز'
  },
  
  pt: {
    'welcome': 'Bem-vindo',
    'loading': 'Carregando...',
    'error': 'Erro',
    'success': 'Sucesso',
    'open': 'Abrir',
    'home': 'Início',
    'marketplace': 'Mercado',
    'dashboard': 'Painel',
    'howToStart': 'Como Começar',
    'about': 'Sobre',
    'connectMetaMask': 'Conectar MetaMask',
    'balance': 'Saldo',
    'createAsset': 'Criar Ativo',
    'startTokenization': 'Iniciar Tokenização',
    'tokenizeRealAssets': 'Tokenizar',
    'realAssets': 'ativos reais',
    'heroSubtitle': 'Cosmo RWA — a primeira plataforma descentralizada para tokenizar imóveis, mercadorias e outros ativos',
    'exploreMarketplace': 'Explorar Mercado',
    'highLiquidity': 'Alta Liquidez',
    'security': 'Segurança',
    'tripleTokenization': 'Tripla Tokenização',
    'tokens': 'Tokens',
    'myAssets': 'Meus Ativos',
    'transactions': 'Transações',
    'totalRevenue': 'Receita Total',
    'quickActions': 'Ações Rápidas',
    'tokenizeYourAsset': 'Tokenizar ativo',
    'tradeAssetTokens': 'Negociar tokens',
    'loansWithTokenCollateral': 'Empréstimos garantidos',
    'defiSwap': 'DeFi Troca',
    'exchangeTokens': 'Trocar tokens',
    'loans': 'Empréstimos',
    'disconnect': 'Desconectar',
    'connectingWallet': 'Conectando carteira...',
    'cosmoBalance': 'Saldo COSMO',
    'bnbBalance': 'Saldo BNB',
    'totalValue': 'Valor Total',
    'perToken': 'por token'
  },
  
  hi: {
    'welcome': 'स्वागत',
    'loading': 'लोड हो रहा है...',
    'error': 'त्रुटि',
    'success': 'सफलता',
    'open': 'खोलें',
    'home': 'होम',
    'marketplace': 'बाज़ार',
    'dashboard': 'डैशबोर्ड',
    'howToStart': 'शुरुआत कैसे करें',
    'about': 'हमारे बारे में',
    'connectMetaMask': 'MetaMask कनेक्ट करें',
    'balance': 'शेष राशि',
    'createAsset': 'एसेट बनाएं',
    'startTokenization': 'टोकनाइज़ेशन शुरू करें',
    'tokenizeRealAssets': 'टोकनाइज़ करें',
    'realAssets': 'वास्तविक संपत्ति',
    'heroSubtitle': 'Cosmo RWA — रियल एस्टेट, सामान और अन्य संपत्तियों को टोकनाइज़ करने के लिए पहला विकेंद्रीकृत प्लेटफॉर्म',
    'exploreMarketplace': 'बाज़ार एक्सप्लोर करें',
    'highLiquidity': 'उच्च तरलता',
    'security': 'सुरक्षा',
    'tripleTokenization': 'ट्रिपल टोकनाइज़ेशन',
    'tokens': 'टोकन',
    'myAssets': 'मेरी संपत्ति',
    'transactions': 'लेन-देन',
    'totalRevenue': 'कुल राजस्व',
    'quickActions': 'त्वरित कार्य',
    'tokenizeYourAsset': 'संपत्ति टोकनाइज़ करें',
    'tradeAssetTokens': 'टोकन ट्रेड करें',
    'loansWithTokenCollateral': 'टोकन जमानत पर ऋण',
    'defiSwap': 'DeFi स्वैप',
    'exchangeTokens': 'टोकन एक्सचेंज',
    'loans': 'ऋण',
    'disconnect': 'डिस्कनेक्ट',
    'connectingWallet': 'वॉलेट कनेक्ट हो रहा है...',
    'cosmoBalance': 'COSMO बैलेंस',
    'bnbBalance': 'BNB बैलेंस',
    'totalValue': 'कुल मूल्य',
    'perToken': 'प्रति टोकन'
  }
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState('ru');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'ru';
    setLanguage(savedLanguage);
  }, []);

  const changeLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.ru] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
